### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by erri120** [ThomasMiz/TrippyGL#3]
Looking into tinkering around with this project a bit, any plans on release a nuget package? Also noticed the project doesn't have any CI testing with Azure DevOps or GitHub Actions.
Should I just use this as a submodule for now?

**Comment by ThomasMiz** [comment]
Hi and thanks for looking into TrippyGL!

I do have plans to release the project as a NuGet package, but I'm waiting to get some more things done before doing so (also, I've never released a NuGet package yet)

I don't have much experience with GitHub Actions nor Azure, if you'd like to help set some things up it'd be very much welcomed and greatly appreciated!

**Comment by ThomasMiz** [comment]
Since at this point every major feature has been implemented and everything appears to be working properly, NuGet packages are finally available!

Since TrippyGL is modularized, it's published as 5 different packages:
https://www.nuget.org/packages/TrippyGL/
https://www.nuget.org/packages/TrippyGL.ImageSharp/
https://www.nuget.org/packages/TrippyGL.Fonts/
https://www.nuget.org/packages/TrippyGL.Fonts.Extensions/
https://www.nuget.org/packages/TrippyGL.Fonts.Building/
